<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>IntroSE.Kanban.Backend</RootNamespace>
    <AssemblyName>IntroSE.Kanban.Backend</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="6.0.0" />
  </ItemGroup>
</Project>
